[
    ElementHandle {
      _disposed: false,
      evaluate: [Function],
      evaluateHandle: [Function],
      _context: FrameExecutionContext {
        evaluate: [AsyncFunction],
        evaluateHandle: [AsyncFunction],
        _delegate: [CRExecutionContext],
        _injectedGeneration: 0,
        frame: [Frame],
        _injectedPromise: [Promise]
      },
      _remoteObject: {
        type: 'object',
        subtype: 'node',
        className: 'HTMLDivElement',
        description: 'div.container',
        objectId: '{"injectedScriptId":7,"id":4}'
      },
      _evaluateInUtility: [AsyncFunction],
      '$eval': [AsyncFunction],
      '$$eval': [AsyncFunction],
      _page: Page {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _closed: false,
        _disconnected: false,
        _pageBindings: Map {},
        _workers: Map {},
        _requestHandlers: [],
        evaluateHandle: [AsyncFunction],
        '$eval': [AsyncFunction],
        '$$eval': [AsyncFunction],
        evaluate: [AsyncFunction],
        _delegate: [CRPage],
        _closedCallback: [Function],
        _closedPromise: [Promise],
        _disconnectedCallback: [Function],
        _disconnectedPromise: [Promise],
        _browserContext: [BrowserContext],
        _state: [Object],
        accessibility: [Accessibility],
        keyboard: [Keyboard],
        mouse: [Mouse],
        _timeoutSettings: [TimeoutSettings],
        _screenshotter: [Screenshotter],
        _frameManager: [FrameManager],
        pdf: [Function: bound pdf] AsyncFunction,
        coverage: [CRCoverage],
        _ownedContext: [BrowserContext],
        [Symbol(kCapture)]: false,
        [Symbol(target)]: [CRTarget]
      }
    },
    ElementHandle {
      _disposed: false,
      evaluate: [Function],
      evaluateHandle: [Function],
      _context: FrameExecutionContext {
        evaluate: [AsyncFunction],
        evaluateHandle: [AsyncFunction],
        _delegate: [CRExecutionContext],
        _injectedGeneration: 0,
        frame: [Frame],
        _injectedPromise: [Promise]
      },
      _remoteObject: {
        type: 'object',
        subtype: 'node',
        className: 'HTMLDivElement',
        description: 'div.container',
        objectId: '{"injectedScriptId":7,"id":5}'
      },
      _evaluateInUtility: [AsyncFunction],
      '$eval': [AsyncFunction],
      '$$eval': [AsyncFunction],
      _page: Page {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _closed: false,
        _disconnected: false,
        _pageBindings: Map {},
        _workers: Map {},
        _requestHandlers: [],
        evaluateHandle: [AsyncFunction],
        '$eval': [AsyncFunction],
        '$$eval': [AsyncFunction],
        evaluate: [AsyncFunction],
        _delegate: [CRPage],
        _closedCallback: [Function],
        _closedPromise: [Promise],
        _disconnectedCallback: [Function],
        _disconnectedPromise: [Promise],
        _browserContext: [BrowserContext],
        _state: [Object],
        accessibility: [Accessibility],
        keyboard: [Keyboard],
        mouse: [Mouse],
        _timeoutSettings: [TimeoutSettings],
        _screenshotter: [Screenshotter],
        _frameManager: [FrameManager],
        pdf: [Function: bound pdf] AsyncFunction,
        coverage: [CRCoverage],
        _ownedContext: [BrowserContext],
        [Symbol(kCapture)]: false,
        [Symbol(target)]: [CRTarget]
      }
    }
  ]